feat(chats): add new fields for peer types
SnejUgal/tbot pull request #2
Opened 2020-12-09 14:22 UTC by uwinx

https://gitlab.com/SnejUgal/tbot/-/issues/59#working-with-groups

2020-12-09 15:31 UTC, SnejUgal requested changes
https://gitlab.com/SnejUgal/tbot/-/merge_requests/294

please format your code: https://gitlab.com/SnejUgal/tbot/-/jobs/900213199

2020-12-09 15:31 UTC, snejugal commented on src/methods/unban_chat_member.rs
> +    /// Configures banning rule, tells to do nothing if the user is not banned.
```suggestion
    /// If `true`, unban only if the user is banned.
```

2020-12-09 15:31 UTC, snejugal commented on src/methods/unban_chat_member.rs
> +    pub const fn unban_if_already_banned(mut self, only_if_banned: bool) -> Self {
```suggestion
    pub const fn only_if_banned(mut self, only_if_banned: bool) -> Self {
```

2020-12-09 15:31 UTC, snejugal commented on src/types/location.rs
> +    pub proximity_alert_radius: Option<u32>,
Since these can only appear for live locations, it'd be better to put them in a separate struct, though one needs to test if all these fields are present at once.

2020-12-09 15:31 UTC, snejugal commented on src/types/chat/location.rs
> +#![deny(clippy::module_name_repetitions)]
This isn't needed here?

2020-12-09 15:31 UTC, SnejUgal commented on src/types/chat/kind.rs
> +        /// [`GetChat`]: ../../methods/struct.GetChat.html
```suggestion
        /// [`GetChat`]: crate::methods::GetChat
```

Since intra-doc links were stabilized in 1.48, please use them.

2020-12-09 15:38 UTC, SnejUgal commented on src/methods/unban_chat_member.rs
> +    pub const fn only_if_banned(mut self, only_if_banned: bool) -> Self {
This method is supposed to be in the first `impl` block.

2020-12-09 15:39 UTC, uwinx commented on src/types/location.rs
> +    pub proximity_alert_radius: Option<u32>,
how are you planning to determine if the location is live?

2020-12-11 16:55 UTC, snejugal requested changes

2020-12-11 16:55 UTC, snejugal commented on src/types/location.rs
> +pub struct LiveConfiguration {
I think `types::location::Live` would be a nicer name.

2020-12-11 16:55 UTC, SnejUgal commented on src/types/location.rs
> +/// Live location struct.
```suggestion
/// Information about a live location.
```

2020-12-11 16:55 UTC, SnejUgal commented on src/types/location.rs
> +    /// The live location configurations.
```suggestion
    /// If this location is a live location, information about it.
```

2020-12-11 16:55 UTC, SnejUgal commented on src/types/location.rs
> +    /// The direction in which user is moving, in degrees; 1-360. For active live locations only.
```suggestion
    /// The direction in which user is moving, in degrees; 1-360.
    /// For active live locations only.
```

2020-12-26 10:23 UTC, SnejUgal requested changes

2020-12-26 10:23 UTC, snejugal commented on src/types/chat/kind.rs
> +        /// The Bio of the other party in a private chat. Returned only
```suggestion
        /// The bio of the other party in a private chat. Returned only
```

2020-12-26 10:23 UTC, snejugal commented on src/types/chat/kind.rs
> +        /// Returned only in [`GetChat`].
```suggestion
        /// If this supergroup is linked to a channel, this field contains the channel's ID. Returned only in [`GetChat`].
```

2020-12-26 10:23 UTC, snejugal commented on src/types/chat/kind.rs
> +        /// Returned only in [`GetChat`].
```suggestion
        /// If this channel has a discussion group, this field contains the group's ID. Returned only in [`GetChat`].
```

2020-12-26 10:23 UTC, snejugal commented on src/types/location.rs
> +    /// The radius of uncertainty for the location, measured in meters; 0-1500
```suggestion
    /// The radius of uncertainty for the location, measured in meters and is in range `0..=1500`.
```

2020-12-26 10:23 UTC, snejugal commented on src/types/location.rs
> +    /// The direction in which user is moving, in degrees; 1-360.
```suggestion
    /// The direction in which user is moving, in degrees and is in range `1..=360`.
```

2020-12-26 10:23 UTC, snejugal commented on src/types/location.rs
> +    /// chat member, in meters. For sent live locations only
```suggestion
    /// chat member, in meters. For sent live locations only.
```

2020-12-26 17:12 UTC, merged