feat: Bot API version 5.2
SnejUgal/tbot pull request #4
Opened 2021-05-10 07:28 UTC by uwinx

- New fields: `SendInvoice::{max_tip_amount, suggested_tip_amounts}`
- Changed field: `SendInvoice::start_parameter` became optional
- Chat actions renamed: `Action::{UploadAudio, RecordAudio}` -> `Action::{UploadVoice, RecordVoice}`

2021-05-10 07:43 UTC, SnejUgal requested changes
Also ensure that `cargo clippy` is happy about your code

2021-05-10 07:43 UTC, snejugal commented on src/methods/send_invoice.rs
> +    pub fn with_max(max_tip: u32) -> Self {
Missing docs

2021-05-10 07:43 UTC, snejugal commented on src/methods/send_invoice.rs
> +        suggested.sort();
This also needs to check that no tip is repeated

2021-05-10 07:43 UTC, snejugal commented on src/methods/send_invoice.rs
> +pub struct Tip {
Needs to be defined in `types::parameters`

2021-05-10 07:43 UTC, snejugal commented on src/methods/send_invoice.rs
> +#[derive(Debug, Clone, Serialize)]
```suggestion
#[derive(Debug, PartialEq, Eq, Clone, Hash, Serialize)]
```

2021-05-10 07:43 UTC, snejugal commented on src/methods/send_invoice.rs
> +             `Tip::suggested_tips` must have at most 4 elements.",
```suggestion
             `Tip::suggested_tips`: must contain from 0 to 4 elements, \
             contains {} elements instead.",
            suggested.len(),
```

2021-05-10 07:43 UTC, snejugal commented on src/methods/send_invoice.rs
> +    #[serde(flatten, skip_serializing_if = "Option::is_none")]
```suggestion
    #[serde(flatten)]
```
Works without `skip_serializing_if` anyway

2021-05-10 07:43 UTC, snejugal commented on src/methods/send_invoice.rs
> +    /// Reflects the `tip` field (`max_tip_amount`, `suggested_tip_amounts`).
Just like in [`SendLocation::live_location`](https://docs.tbot.rs/methods/struct.SendLocation.html#method.live_location), there's no need to specify the exact reflected parameters here, it should be documented in `Tip`.

2021-05-10 07:43 UTC, snejugal commented on src/types/chat/action.rs
> +    /// About to send a generated voice-audio.
```suggestion
    /// About to send a generated voice.
```
(or `a generated voice message` if `voice` on its own sounds a bit awkward)

2021-05-10 07:43 UTC, snejugal commented on src/types/invoice.rs
> +    pub start_parameter: Option<String>,
Hmm, this is an interesting one since it's still a non-optional field per [docs](https://core.telegram.org/bots/api#invoice). This needs research

2021-05-10 07:52 UTC, uwinx commented on src/types/chat/action.rs
> +    /// About to send a generated voice-audio.
tbh, I disagree with all these "About to `send`..". can't we rename those to "Status: sending/recording"

2021-05-10 07:55 UTC, uwinx commented on src/types/invoice.rs
> +    pub start_parameter: Option<String>,
Agree, found it unclear too. I guess it's generated when required when we don't pass it to `sendVoice`

2021-05-10 09:12 UTC, SnejUgal requested changes

2021-05-10 09:12 UTC, SnejUgal commented on src/types/parameters.rs
> +pub mod tip;
What's the point of `pub` if it only contains one type?

2021-05-10 09:12 UTC, SnejUgal commented on src/types/parameters/tip.rs
> +    /// Initialize a `Tip` with a given max tip amount.
```suggestion
    /// Constructs a `Tip` with the given max tip amount.
    /// Reflects the `max_tip_amount` parameter.
```

2021-05-10 09:12 UTC, SnejUgal commented on src/types/parameters/tip.rs
> +    /// Panics if there are more than 4 elements.
Not only as seen from the implementation

2021-05-10 09:12 UTC, SnejUgal commented on src/types/parameters/tip.rs
> +            suggested[3] <= self.max_tip_amount,
What if there are less than 4 elements?

2021-05-10 09:14 UTC, uwinx commented on src/types/parameters/tip.rs
> +            suggested[3] <= self.max_tip_amount,
that's an oopsie. my bad.

2021-05-10 11:29 UTC, SnejUgal commented on src/types/invoice.rs
> +    pub start_parameter: Option<String>,
just tested it:

```
Invoice {
    title: "A crab",
    description: "Have you ever come across a heisenbug in your program? No more! Our crab will take all bugs out of your program for you.",
    start_parameter: Some(
        "",
    ),
    currency: "RUB",
    total_amount: 10000,
}
```

Maybe we can parse empty strings as `None`, but do we really need it?

2021-05-10 11:32 UTC, uwinx commented on src/types/invoice.rs
> +    pub start_parameter: Option<String>,
well, yes I think.

2021-05-10 11:35 UTC, SnejUgal requested changes

2021-05-10 11:35 UTC, SnejUgal commented on src/bot.rs
>      pub fn send_invoice(
Remove the `#[allow(clippy::too_many_arguments)]` attribute above as it's no longer needed.

2021-05-10 11:35 UTC, SnejUgal commented on src/contexts/methods/message.rs
>      #[allow(clippy::too_many_arguments)]
```suggestion
```

2021-05-10 11:35 UTC, SnejUgal commented on src/contexts/methods/message.rs
>      #[allow(clippy::too_many_arguments)]
```suggestion
```

2021-05-10 11:35 UTC, SnejUgal commented on src/methods/send_invoice.rs
> +    }
Move it to the top so that it'll be on top in docs too

2021-05-10 11:35 UTC, SnejUgal commented on src/types/input_message_content/invoice.rs
> +pub struct Invoice {
So how do I construct this type?

2021-05-10 11:35 UTC, SnejUgal commented on src/types/parameters/tip.rs
> +    #[must_use]
Better add this `#[must_use]` to the struct defintion

2021-05-10 12:11 UTC, uwinx commented on src/types/invoice.rs
> +    pub start_parameter: Option<String>,
well, actually no. it's easy to check whether the string is empty and telegram makes sense returning empty string, so won't implement in this PR.

2021-05-10 13:22 UTC, snejugal requested changes
Will make a MR on GitLab a bit later

2021-05-10 13:22 UTC, snejugal commented on src/methods/send_invoice.rs
>      #[allow(clippy::too_many_arguments)] // I know, brother
```suggestion
```

2021-05-10 13:22 UTC, snejugal commented on src/types/inline_query.rs
> +    pub chat_type: Option<ChatKind>,
This field needs to be added to `contexts::Inline`.

2021-05-10 13:22 UTC, snejugal commented on src/types/parameters/tip.rs
> +    /// At most 4 suggestions can be specified.
Can you also document that `tbot` will sort provided tips since this is required by Bot API?

2021-05-10 13:39 UTC, snejugal commented
MR on GitLab: https://gitlab.com/SnejUgal/tbot/-/merge_requests/332

2021-05-11 07:43 UTC, SnejUgal requested changes

2021-05-11 07:43 UTC, snejugal commented on src/types/inline_query.rs
> +    pub chat_type: Option<ChatKind>,
```suggestion
    /// The type of chat inline query was sent from.
    #[serde(rename = "chat_type")]
    pub chat_kind: Option<ChatKind>,
```

2021-05-11 07:43 UTC, snejugal commented on src/types/parameters/tip.rs
> +    /// This method automatically sorts the data given.
```suggestion
    /// This method automatically sorts provided tips.
```

2021-05-11 07:43 UTC, snejugal commented on examples/payment.rs
> +            let price = [LabeledPrice::new(TITLE, 10_000)];
```suggestion
            let price = [LabeledPrice::new(TITLE, 100_00)];
```

The underscore here was originally used to separate the fractional part from the integer one.

2021-05-11 07:43 UTC, snejugal commented on examples/payment.rs
> +            let tip = Tip::with_max(20_00).suggested_tips([19_06, 20_00]);
Actually `invoice` construction can be merged into one expression. But then it's better to move the photo's URL to a `const` above.

2021-07-11 12:55 UTC, merged